class TwitterConfig(object):
    TWITTER_CONSUMER_KEY = 'zYZS8rzUAxhPFRcKBenhPQ'
    TWITTER_CONSUMER_SECRET = 'AgXBoAjx3QuBtUQ60bEWFupNYGLITa1dTY3ljWw'

    TWITTER_ACCESS_TOKEN = '17865969-0v1cRUbjRVDbHhVcODcOvSvocyDlTYGLoc4Dee3MZ'
    TWITTER_ACCESS_TOKEN_SECRET = '9zVnJXmqQKy2EJweHO26GjyI3yv2C3HhXizXpqbToU'
